Update chat RFC status to ACCEPTED
enarx/rfcs pull request #35
Opened 2020-05-27 15:44 UTC by mbestavros

2020-05-28 11:54 UTC, haraldh submitted a review, later dismissed

2020-05-28 14:09 UTC, connorkuehl requested changes

2020-05-28 14:09 UTC, connorkuehl commented on 00000-migrate-enarx-public-chat/README.md
> +- Status: [ACCEPTED](/README.md#acepted)
Typo: ~~acepted~~ -> accepted

2020-05-28 14:20 UTC, mbestavros commented on 00000-migrate-enarx-public-chat/README.md
> +- Status: [ACCEPTED](/README.md#acepted)
Fixed. Thanks!

2020-05-28 20:00 UTC, lkatalin reviewed
Is this PR only for the chat program itself and not the RFC about the chat program? The RFC about the chat program needs to update the chat link for Rocket.chat.

But re: the program itself, I have accepted it FWIW.

2020-05-28 20:06 UTC, npmccallum commented
> Is this PR only for the chat program itself and not the RFC about the chat program? The RFC about the chat program needs to update the chat link for Rocket.chat.
> 
> But re: the program itself, I have accepted it FWIW.

@mbestavros Please fix this in a separate PR.

2020-06-01 14:30 UTC, MikeCamel approved these changes

2020-06-01 15:07 UTC, connorkuehl approved these changes

2020-06-01 15:34 UTC, lkatalin approved these changes

2020-06-01 21:55 UTC, axelsimon approved these changes

2020-06-02 06:26 UTC, ueno approved these changes

2020-06-02 11:45 UTC, npmccallum commented
Seeing that we have consensus, the status change is approved.

2020-06-02 11:45 UTC, merged